language: python
python:
    - '2.7'
    - '3.6'
before_install:
    - sudo apt-get -qq update
    - pip install codecov
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
 
    - echo $TRAVIS_PYTHON_VERSION
    - conda config --set always_yes yes --set changeps1 no
    - conda create -n travis python=$TRAVIS_PYTHON_VERSION -f conda/dev-environment.yml
    - if [ -f conda/dev-environment-py${TRAVIS_PYTHON_VERSION}.yml ]; then conda env update -n travis -f conda/dev-environment-py${TRAVIS_PYTHON_VERSION}.yml; fi
    - source activate travis
    - pip install --upgrade pytest numpy netCDF4
script:
    - python --version
    - py.test -s test/test_nc2nc.py test/test_nccopy.py
after_success:
    - coverage run --source=n2nc,nc_compress,test/test_nc2nc.py,test/test_nc_compress.py -m py.test
    - codecov
